# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/src/cmake-3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/src/cmake-3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jucilab/learn-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jucilab/learn-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/src/cmake-3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/src/cmake-3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jucilab/learn-cpp/CMakeFiles /home/jucilab/learn-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jucilab/learn-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reverse_list

# Build rule for target.
reverse_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reverse_list
.PHONY : reverse_list

# fast build rule for target.
reverse_list/fast:
	$(MAKE) -f CMakeFiles/reverse_list.dir/build.make CMakeFiles/reverse_list.dir/build
.PHONY : reverse_list/fast

#=============================================================================
# Target rules for targets named 01_package

# Build rule for target.
01_package: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 01_package
.PHONY : 01_package

# fast build rule for target.
01_package/fast:
	$(MAKE) -f CMakeFiles/01_package.dir/build.make CMakeFiles/01_package.dir/build
.PHONY : 01_package/fast

#=============================================================================
# Target rules for targets named quick_pow

# Build rule for target.
quick_pow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quick_pow
.PHONY : quick_pow

# fast build rule for target.
quick_pow/fast:
	$(MAKE) -f CMakeFiles/quick_pow.dir/build.make CMakeFiles/quick_pow.dir/build
.PHONY : quick_pow/fast

#=============================================================================
# Target rules for targets named quick_sort

# Build rule for target.
quick_sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quick_sort
.PHONY : quick_sort

# fast build rule for target.
quick_sort/fast:
	$(MAKE) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/build
.PHONY : quick_sort/fast

#=============================================================================
# Target rules for targets named test_size

# Build rule for target.
test_size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_size
.PHONY : test_size

# fast build rule for target.
test_size/fast:
	$(MAKE) -f CMakeFiles/test_size.dir/build.make CMakeFiles/test_size.dir/build
.PHONY : test_size/fast

#=============================================================================
# Target rules for targets named test_ran

# Build rule for target.
test_ran: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ran
.PHONY : test_ran

# fast build rule for target.
test_ran/fast:
	$(MAKE) -f CMakeFiles/test_ran.dir/build.make CMakeFiles/test_ran.dir/build
.PHONY : test_ran/fast

#=============================================================================
# Target rules for targets named tree_array

# Build rule for target.
tree_array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree_array
.PHONY : tree_array

# fast build rule for target.
tree_array/fast:
	$(MAKE) -f CMakeFiles/tree_array.dir/build.make CMakeFiles/tree_array.dir/build
.PHONY : tree_array/fast

#=============================================================================
# Target rules for targets named test_rand

# Build rule for target.
test_rand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rand
.PHONY : test_rand

# fast build rule for target.
test_rand/fast:
	$(MAKE) -f CMakeFiles/test_rand.dir/build.make CMakeFiles/test_rand.dir/build
.PHONY : test_rand/fast

#=============================================================================
# Target rules for targets named test_absfloat

# Build rule for target.
test_absfloat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_absfloat
.PHONY : test_absfloat

# fast build rule for target.
test_absfloat/fast:
	$(MAKE) -f CMakeFiles/test_absfloat.dir/build.make CMakeFiles/test_absfloat.dir/build
.PHONY : test_absfloat/fast

#=============================================================================
# Target rules for targets named test_char

# Build rule for target.
test_char: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_char
.PHONY : test_char

# fast build rule for target.
test_char/fast:
	$(MAKE) -f CMakeFiles/test_char.dir/build.make CMakeFiles/test_char.dir/build
.PHONY : test_char/fast

algorithm/01_package.o: algorithm/01_package.cc.o

.PHONY : algorithm/01_package.o

# target to build an object file
algorithm/01_package.cc.o:
	$(MAKE) -f CMakeFiles/01_package.dir/build.make CMakeFiles/01_package.dir/algorithm/01_package.cc.o
.PHONY : algorithm/01_package.cc.o

algorithm/01_package.i: algorithm/01_package.cc.i

.PHONY : algorithm/01_package.i

# target to preprocess a source file
algorithm/01_package.cc.i:
	$(MAKE) -f CMakeFiles/01_package.dir/build.make CMakeFiles/01_package.dir/algorithm/01_package.cc.i
.PHONY : algorithm/01_package.cc.i

algorithm/01_package.s: algorithm/01_package.cc.s

.PHONY : algorithm/01_package.s

# target to generate assembly for a file
algorithm/01_package.cc.s:
	$(MAKE) -f CMakeFiles/01_package.dir/build.make CMakeFiles/01_package.dir/algorithm/01_package.cc.s
.PHONY : algorithm/01_package.cc.s

algorithm/quick_pow.o: algorithm/quick_pow.cc.o

.PHONY : algorithm/quick_pow.o

# target to build an object file
algorithm/quick_pow.cc.o:
	$(MAKE) -f CMakeFiles/quick_pow.dir/build.make CMakeFiles/quick_pow.dir/algorithm/quick_pow.cc.o
.PHONY : algorithm/quick_pow.cc.o

algorithm/quick_pow.i: algorithm/quick_pow.cc.i

.PHONY : algorithm/quick_pow.i

# target to preprocess a source file
algorithm/quick_pow.cc.i:
	$(MAKE) -f CMakeFiles/quick_pow.dir/build.make CMakeFiles/quick_pow.dir/algorithm/quick_pow.cc.i
.PHONY : algorithm/quick_pow.cc.i

algorithm/quick_pow.s: algorithm/quick_pow.cc.s

.PHONY : algorithm/quick_pow.s

# target to generate assembly for a file
algorithm/quick_pow.cc.s:
	$(MAKE) -f CMakeFiles/quick_pow.dir/build.make CMakeFiles/quick_pow.dir/algorithm/quick_pow.cc.s
.PHONY : algorithm/quick_pow.cc.s

algorithm/quick_sort.o: algorithm/quick_sort.cc.o

.PHONY : algorithm/quick_sort.o

# target to build an object file
algorithm/quick_sort.cc.o:
	$(MAKE) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/algorithm/quick_sort.cc.o
.PHONY : algorithm/quick_sort.cc.o

algorithm/quick_sort.i: algorithm/quick_sort.cc.i

.PHONY : algorithm/quick_sort.i

# target to preprocess a source file
algorithm/quick_sort.cc.i:
	$(MAKE) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/algorithm/quick_sort.cc.i
.PHONY : algorithm/quick_sort.cc.i

algorithm/quick_sort.s: algorithm/quick_sort.cc.s

.PHONY : algorithm/quick_sort.s

# target to generate assembly for a file
algorithm/quick_sort.cc.s:
	$(MAKE) -f CMakeFiles/quick_sort.dir/build.make CMakeFiles/quick_sort.dir/algorithm/quick_sort.cc.s
.PHONY : algorithm/quick_sort.cc.s

algorithm/reverse_list.o: algorithm/reverse_list.cc.o

.PHONY : algorithm/reverse_list.o

# target to build an object file
algorithm/reverse_list.cc.o:
	$(MAKE) -f CMakeFiles/reverse_list.dir/build.make CMakeFiles/reverse_list.dir/algorithm/reverse_list.cc.o
	$(MAKE) -f CMakeFiles/test_ran.dir/build.make CMakeFiles/test_ran.dir/algorithm/reverse_list.cc.o
.PHONY : algorithm/reverse_list.cc.o

algorithm/reverse_list.i: algorithm/reverse_list.cc.i

.PHONY : algorithm/reverse_list.i

# target to preprocess a source file
algorithm/reverse_list.cc.i:
	$(MAKE) -f CMakeFiles/reverse_list.dir/build.make CMakeFiles/reverse_list.dir/algorithm/reverse_list.cc.i
	$(MAKE) -f CMakeFiles/test_ran.dir/build.make CMakeFiles/test_ran.dir/algorithm/reverse_list.cc.i
.PHONY : algorithm/reverse_list.cc.i

algorithm/reverse_list.s: algorithm/reverse_list.cc.s

.PHONY : algorithm/reverse_list.s

# target to generate assembly for a file
algorithm/reverse_list.cc.s:
	$(MAKE) -f CMakeFiles/reverse_list.dir/build.make CMakeFiles/reverse_list.dir/algorithm/reverse_list.cc.s
	$(MAKE) -f CMakeFiles/test_ran.dir/build.make CMakeFiles/test_ran.dir/algorithm/reverse_list.cc.s
.PHONY : algorithm/reverse_list.cc.s

algorithm/tree_array.o: algorithm/tree_array.cc.o

.PHONY : algorithm/tree_array.o

# target to build an object file
algorithm/tree_array.cc.o:
	$(MAKE) -f CMakeFiles/tree_array.dir/build.make CMakeFiles/tree_array.dir/algorithm/tree_array.cc.o
.PHONY : algorithm/tree_array.cc.o

algorithm/tree_array.i: algorithm/tree_array.cc.i

.PHONY : algorithm/tree_array.i

# target to preprocess a source file
algorithm/tree_array.cc.i:
	$(MAKE) -f CMakeFiles/tree_array.dir/build.make CMakeFiles/tree_array.dir/algorithm/tree_array.cc.i
.PHONY : algorithm/tree_array.cc.i

algorithm/tree_array.s: algorithm/tree_array.cc.s

.PHONY : algorithm/tree_array.s

# target to generate assembly for a file
algorithm/tree_array.cc.s:
	$(MAKE) -f CMakeFiles/tree_array.dir/build.make CMakeFiles/tree_array.dir/algorithm/tree_array.cc.s
.PHONY : algorithm/tree_array.cc.s

tests/test_absfloat.o: tests/test_absfloat.cc.o

.PHONY : tests/test_absfloat.o

# target to build an object file
tests/test_absfloat.cc.o:
	$(MAKE) -f CMakeFiles/test_absfloat.dir/build.make CMakeFiles/test_absfloat.dir/tests/test_absfloat.cc.o
.PHONY : tests/test_absfloat.cc.o

tests/test_absfloat.i: tests/test_absfloat.cc.i

.PHONY : tests/test_absfloat.i

# target to preprocess a source file
tests/test_absfloat.cc.i:
	$(MAKE) -f CMakeFiles/test_absfloat.dir/build.make CMakeFiles/test_absfloat.dir/tests/test_absfloat.cc.i
.PHONY : tests/test_absfloat.cc.i

tests/test_absfloat.s: tests/test_absfloat.cc.s

.PHONY : tests/test_absfloat.s

# target to generate assembly for a file
tests/test_absfloat.cc.s:
	$(MAKE) -f CMakeFiles/test_absfloat.dir/build.make CMakeFiles/test_absfloat.dir/tests/test_absfloat.cc.s
.PHONY : tests/test_absfloat.cc.s

tests/test_char.o: tests/test_char.cc.o

.PHONY : tests/test_char.o

# target to build an object file
tests/test_char.cc.o:
	$(MAKE) -f CMakeFiles/test_char.dir/build.make CMakeFiles/test_char.dir/tests/test_char.cc.o
.PHONY : tests/test_char.cc.o

tests/test_char.i: tests/test_char.cc.i

.PHONY : tests/test_char.i

# target to preprocess a source file
tests/test_char.cc.i:
	$(MAKE) -f CMakeFiles/test_char.dir/build.make CMakeFiles/test_char.dir/tests/test_char.cc.i
.PHONY : tests/test_char.cc.i

tests/test_char.s: tests/test_char.cc.s

.PHONY : tests/test_char.s

# target to generate assembly for a file
tests/test_char.cc.s:
	$(MAKE) -f CMakeFiles/test_char.dir/build.make CMakeFiles/test_char.dir/tests/test_char.cc.s
.PHONY : tests/test_char.cc.s

tests/test_rand.o: tests/test_rand.cc.o

.PHONY : tests/test_rand.o

# target to build an object file
tests/test_rand.cc.o:
	$(MAKE) -f CMakeFiles/test_rand.dir/build.make CMakeFiles/test_rand.dir/tests/test_rand.cc.o
.PHONY : tests/test_rand.cc.o

tests/test_rand.i: tests/test_rand.cc.i

.PHONY : tests/test_rand.i

# target to preprocess a source file
tests/test_rand.cc.i:
	$(MAKE) -f CMakeFiles/test_rand.dir/build.make CMakeFiles/test_rand.dir/tests/test_rand.cc.i
.PHONY : tests/test_rand.cc.i

tests/test_rand.s: tests/test_rand.cc.s

.PHONY : tests/test_rand.s

# target to generate assembly for a file
tests/test_rand.cc.s:
	$(MAKE) -f CMakeFiles/test_rand.dir/build.make CMakeFiles/test_rand.dir/tests/test_rand.cc.s
.PHONY : tests/test_rand.cc.s

tests/test_size.o: tests/test_size.cc.o

.PHONY : tests/test_size.o

# target to build an object file
tests/test_size.cc.o:
	$(MAKE) -f CMakeFiles/test_size.dir/build.make CMakeFiles/test_size.dir/tests/test_size.cc.o
.PHONY : tests/test_size.cc.o

tests/test_size.i: tests/test_size.cc.i

.PHONY : tests/test_size.i

# target to preprocess a source file
tests/test_size.cc.i:
	$(MAKE) -f CMakeFiles/test_size.dir/build.make CMakeFiles/test_size.dir/tests/test_size.cc.i
.PHONY : tests/test_size.cc.i

tests/test_size.s: tests/test_size.cc.s

.PHONY : tests/test_size.s

# target to generate assembly for a file
tests/test_size.cc.s:
	$(MAKE) -f CMakeFiles/test_size.dir/build.make CMakeFiles/test_size.dir/tests/test_size.cc.s
.PHONY : tests/test_size.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... reverse_list"
	@echo "... 01_package"
	@echo "... edit_cache"
	@echo "... quick_pow"
	@echo "... quick_sort"
	@echo "... test_size"
	@echo "... test_ran"
	@echo "... tree_array"
	@echo "... test_rand"
	@echo "... test_absfloat"
	@echo "... test_char"
	@echo "... algorithm/01_package.o"
	@echo "... algorithm/01_package.i"
	@echo "... algorithm/01_package.s"
	@echo "... algorithm/quick_pow.o"
	@echo "... algorithm/quick_pow.i"
	@echo "... algorithm/quick_pow.s"
	@echo "... algorithm/quick_sort.o"
	@echo "... algorithm/quick_sort.i"
	@echo "... algorithm/quick_sort.s"
	@echo "... algorithm/reverse_list.o"
	@echo "... algorithm/reverse_list.i"
	@echo "... algorithm/reverse_list.s"
	@echo "... algorithm/tree_array.o"
	@echo "... algorithm/tree_array.i"
	@echo "... algorithm/tree_array.s"
	@echo "... tests/test_absfloat.o"
	@echo "... tests/test_absfloat.i"
	@echo "... tests/test_absfloat.s"
	@echo "... tests/test_char.o"
	@echo "... tests/test_char.i"
	@echo "... tests/test_char.s"
	@echo "... tests/test_rand.o"
	@echo "... tests/test_rand.i"
	@echo "... tests/test_rand.s"
	@echo "... tests/test_size.o"
	@echo "... tests/test_size.i"
	@echo "... tests/test_size.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

